---
language: go
go:
  - "1.12.4"

python:
  - 2.7

services: docker

env:
  - distro: ubuntu1204
  - distro: ubuntu1210
  - distro: ubuntu1304
  - distro: ubuntu1310
  - distro: ubuntu1404
  - distro: ubuntu1410
  - distro: ubuntu1504
  - distro: ubuntu1510
  - distro: ubuntu1604
  - distro: ubuntu1610
  - distro: ubuntu1704
  - distro: ubuntu1710
  - distro: ubuntu1804
  - distro: ubuntu1810
  - distro: centos7
  - distro: debian8
  - distro: debian9
  - distro: debian10
  - distro: fedora24
  - distro: fedora25
  - distro: fedora26
  - distro: fedora27
  - distro: fedora28

before_install:
  # Install golang deps
  - GO111MODULE=on go get github.com/fubarhouse/ansible-role-tester

script:
  # Test the role from inside the container using the segmented commands.
  - cd ${TRAVIS_BUILD_DIR}
  - ansible-role-tester run --name travis_test --user fubarhouse --distribution ${distro}
  - ansible-role-tester install --name travis_test
  - ansible-role-tester test --name travis_test --playbook ./tests/test.yml
  - ansible-role-tester destroy --name travis_test
  - sleep 10

notifications:
  slack: fubarhouse:upHoIzmKb4ikkBOt2cOwgKXY
  webhooks: https://galaxy.ansible.com/api/v1/notifications/