---
# main tasks file for fubarhouse-golang

- name: "Include tasks gathering system information"
  include_tasks: setup.yml

- name: "Include tasks to clean installation"
  include_tasks: cleanup.yml
  when: go_install_clean

- name: "Include tasks for installation"
  include_tasks: install.yml
  when: (not go_binary.stat.exists) or ((current_go_version is not defined) or
        (expected_go_version_output|string not in current_go_version.stdout|default('')) or
        go_install_clean) and
        (go_install_clean) and
        (not go_uninstall)

- name: "Include tasks for Go Get"
  include_tasks: go-get.yml
  when: (go_get.0 is defined) and
        (not go_uninstall|bool)

- name: "Include tasks for Go Install"
  include_tasks: go-install.yml
  when: (go_install.0 is defined) and
        (not go_uninstall)

- name: "Include tasks for setting Go permissions"
  include_tasks: perm.yml
  when: not go_uninstall

- name: "Include tasks for shell installation"
  include_tasks: install-shell.yml
  when: golang_shell_profile is defined